name: "ci-msrv"
on:
  pull_request:
  push:
    branches:
      - master
      - main
  merge_group:
  schedule:
    - cron: '00 06 * * *'
jobs:
  # MSRV check and e2e test
  msrv:
    name: msrv
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        build: [ ubuntu, macos ] # [, windows] ... Disabled Windows for now, see #1036
        include:
          - build: ubuntu
            os: ubuntu-latest

          - build: macos
            os: macos-latest

    #          - build: windows
    #            os: windows-latest
    continue-on-error: true
    steps:
      - name: checkout_repo
        uses: actions/checkout@v4
      - name: install_rust
        uses: dtolnay/rust-toolchain@stable
      - name: install_cargo_msrv
        if: matrix.build == 'ubuntu'
        run: cargo install cargo-msrv
      - name: install_cargo_msrv_no_default
        if: matrix.build != 'ubuntu'
        run: cargo install cargo-msrv --no-default-features
      - name: version_of_cargo_msrv
        run: cargo msrv --version
      - name: run_cargo_msrv
        run: cargo msrv verify --output-format json
      - name: run_cargo_msrv_on_verify_failure
        if: ${{ failure() }}
        run: cargo msrv find --output-format json

  # The same as the 'msrv' job, except it takes the latest release, including beta releases
  msrv_pre_release:
    name: msrv_pre_release
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: checkout_repo
        uses: actions/checkout@v4
      - name: install_rust
        uses: dtolnay/rust-toolchain@stable
      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-binstall
      - name: install_cargo_msrv_bin
        run: cargo binstall --version 0.16.2 --no-confirm cargo-msrv
      - name: version_of_cargo_msrv
        run: cargo msrv --version
      - name: run_cargo_msrv
        run: cargo msrv verify --output-format json
      - name: run_cargo_msrv_on_verify_failure
        if: ${{ failure() }}
        run: cargo msrv find --output-format json

  # The same as the 'msrv' job, except it takes the latest development branch, as a form of test
  # we don't use --all-features here!
  msrv_development:
    name: msrv_development
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: checkout_repo
        uses: actions/checkout@v4
      - name: install_rust
        uses: dtolnay/rust-toolchain@stable
      - name: install_cargo_msrv
        run: cargo install --git https://github.com/foresterre/cargo-msrv.git cargo-msrv
      - name: version_of_cargo_msrv
        run: cargo msrv --version
      - name: run_cargo_msrv
        run: cargo msrv verify --output-format json
      - name: run_cargo_msrv_on_verify_failure
        if: ${{ failure() }}
        run: cargo msrv find --output-format json

  minimal_versions:
    name: msrv_with_minimal_versions
    runs-on: ubuntu-latest
    steps:
      - name: checkout_repo
        uses: actions/checkout@v4
      - name: install_rust
        uses: dtolnay/rust-toolchain@nightly
      - name: generate_lockfile_with_minimal_versions
        run: cargo generate-lockfile -Z minimal-versions
      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-binstall
      - name: install_cargo_msrv
        run: cargo binstall --no-confirm cargo-msrv
      - name: check_minimal_versions
        run: cargo msrv verify -- cargo check --locked
